version: '2.1'

services:
  openmrs-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
    healthcheck:
      test: "exit 0"
    ports:
      - "3306:3306"
    volumes:
      - openmrs-mysql-data:/var/lib/mysql

  openmrs:
    restart: "always"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - openmrs-mysql
    ports:
      - "8080-8086:8080"
    cpus: 0.5
    mem_limit: 500m
    environment:
      DB_DATABASE: openmrs
      DB_HOST: localhost:3306
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs-data:/usr/local/tomcat/.OpenMRS/
      - /usr/local/tomcat/.OpenMRS/modules/ # do not store modules in data
      - /usr/local/tomcat/.OpenMRS/owa/ # do not store owa in data
    # CPU limits
    # memory limits
    # Specifiy within the command
    # monitoring - Docker Compose

volumes:
   openmrs-mysql-data:
   openmrs-data:
